const plusTwo = n => {
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  console.log('===')
  return n + 2
}

export default plusTwo
